maisjob/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from apps.agencia.views import AcaoListView, AcaoCreateView, AcaoUpdateView, AcaoDeleteView, \
    AgenciaListView, AgenciaCreateView, AgenciaUpdateView, AgenciaDeleteView
from apps.agencia.viewsets import AgenciaListViewSet
from apps.core.views import HomeView, LogoutView, LoginView
from apps.core.viewsets import EstadoListViewSet
from apps.job.views import JobListView, JobCreateView, JobUpdateView, JobDeleteView, TipoJobListView, TipoJobCreateView, \
    TipoJobUpdateView, TipoJobDeleteView, CandidaturaView, CandidaturaJogoView
from apps.job.viewsets import JobListViewSet, TipoJobViewSet, JobViewSet, CandidaturaViewSet, CandidaturaStatusViewSet
from apps.promotor.views import PromotorCredenciadoListView, PromotorCredenciadoUpdateView
from apps.promotor.viewsets import PromotorCreateViewSet, CorDaPeleListViewSet, CorDoCabeloListViewSet, \
    CorDosOlhosListViewSet, LoginPromotorViewSet, PromotorViewSet, PromotorGetViewSet, PromotorUpdateViewSet, \
    CoresViewSet, ImagemCreateViewSet

router = DefaultRouter()
router.register(r'tipo-job', TipoJobViewSet)
router.register(r'job', JobViewSet)
router.register(r'promotor', PromotorViewSet)
router.register(r'agencia-list', AgenciaListViewSet)
router.register(r'estado-list', EstadoListViewSet)
router.register(r'candidatura', CandidaturaViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/imagem-save/', ImagemCreateViewSet.as_view()),
    url(r'^api/login-promotor/', LoginPromotorViewSet.as_view()),
    url(r'^api/job-list/', JobListViewSet.as_view()),
    url(r'^api/promotor/', PromotorGetViewSet.as_view()),
    url(r'^api/promotor-create/', PromotorCreateViewSet.as_view()),
    url(r'^api/promotor-update/(?P<pk>[0-9]+)/', PromotorUpdateViewSet.as_view()),
    url(r'^api/candidatura/(?P<candidatura>[0-9]+)/status/(?P<status>[0-9]+)/', CandidaturaStatusViewSet.as_view()),
    url(r'^api/cordapele-list/', CorDaPeleListViewSet.as_view()),
    url(r'^api/cordocabelo-list/', CorDoCabeloListViewSet.as_view()),
    url(r'^api/cordosolhos-list/', CorDosOlhosListViewSet.as_view()),
    url(r'^api/cores/', CoresViewSet.as_view()),

    url(regex='^login/$', view=LoginView.as_view(), name='login'),
    url(regex='^logout/$', view=LogoutView.as_view(), name='logout'),
    url(regex='^$', view=HomeView.as_view(), name='home'),

    url(regex='^cadastros/agencia/$', view=AgenciaListView.as_view(), name='cadastros-agencia-list'),
    url(regex='^cadastros/agencia/create$', view=AgenciaCreateView.as_view(), name='cadastros-agencia-create'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/$', view=AgenciaUpdateView.as_view(), name='cadastros-agencia-update'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/delete/$', view=AgenciaDeleteView.as_view(),
        name='cadastros-agencia-delete'),

    url(regex='^cadastros/acao/$', view=AcaoListView.as_view(), name='cadastros-acao-list'),
    url(regex='^cadastros/acao/create$', view=AcaoCreateView.as_view(), name='cadastros-acao-create'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/$', view=AcaoUpdateView.as_view(), name='cadastros-acao-update'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/delete/$', view=AcaoDeleteView.as_view(), name='cadastros-acao-delete'),

    url(regex='^cadastros/tipojob/$', view=TipoJobListView.as_view(), name='cadastros-tipojob-list'),
    url(regex='^cadastros/tipojob/create$', view=TipoJobCreateView.as_view(), name='cadastros-tipojob-create'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/$', view=TipoJobUpdateView.as_view(), name='cadastros-tipojob-update'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/delete/$', view=TipoJobDeleteView.as_view(),
        name='cadastros-tipojob-delete'),

    url(regex='^cadastros/job/$', view=JobListView.as_view(), name='cadastros-job-list'),
    url(regex='^cadastros/job/create$', view=JobCreateView.as_view(), name='cadastros-job-create'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/$', view=JobUpdateView.as_view(), name='cadastros-job-update'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/delete/$', view=JobDeleteView.as_view(), name='cadastros-job-delete'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),

    url(regex='^candidatura/list/$', view=CandidaturaView.as_view(), name='candidatura-list'),
    url(regex='^candidatura/jogo/$', view=CandidaturaJogoView.as_view(), name='candidatura-jogo'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),
]

if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

apps/job/models.py
from django.db import models

# Create your models here.
from simple_history.models import HistoricalRecords


class TipoJob(models.Model):
    HORA = 1
    DIARIA = 2
    SEMANA = 3
    MES = 4

    MODOS_PAGAMENTOS = (
        (HORA, 'Pagamento por hora'),
        (DIARIA, 'Pagamento por dia'),
        (SEMANA, 'Pagamento por semana'),
        (MES, 'Pagamento por mês')
    )

    descricao = models.CharField(max_length=255)
    modo_pagamento_sugerido = models.PositiveIntegerField(choices=MODOS_PAGAMENTOS)
    history = HistoricalRecords(table_name='job_tipojob_history')

    def __str__(self):
        return self.descricao


class Job(models.Model):
    PREFIRO_NAO_DIZER = 1
    MASCULINO = 2
    FEMININO = 3

    SEXO = (
        (PREFIRO_NAO_DIZER, 'Prefiro não dizer'),
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )

    acao = models.ForeignKey(to='agencia.Acao', on_delete=models.PROTECT, related_name='jobs')
    tipo = models.ForeignKey(to='TipoJob', on_delete=models.PROTECT, related_name='jobs')
    modo_pagamento = models.PositiveIntegerField(choices=TipoJob.MODOS_PAGAMENTOS)
    quantidade_vagas_totais = models.IntegerField()
    quantidade_vagas_disponiveis = models.IntegerField()
    quantidade_de_modo_pagamento = models.IntegerField()
    cache_por_modo_pagamento = models.FloatField()
    cache_individual = models.FloatField()
    cache_total = models.FloatField()
    observacao = models.CharField(max_length=255, null=True)

    perfil_sexo = models.PositiveIntegerField(choices=SEXO, null=True)
    perfil_idade_minima = models.IntegerField(null=True)
    perfil_idade_maxima = models.IntegerField(null=True)
    perfil_altura_minima = models.FloatField(null=True)
    perfil_altura_maxima = models.FloatField(null=True)

    history = HistoricalRecords(table_name='job_job_history')

    def subtrair_disponnivel(self):
        job = Job.objects.filter(id=self.id)
        job.update(quantidade_vagas_disponiveis=job[0].quantidade_vagas_disponiveis - 1)

    def adicionar_disponnivel(self):
        job = Job.objects.filter(id=self.id)
        job.update(quantidade_vagas_disponiveis=job[0].quantidade_vagas_disponiveis + 1)

    def __str__(self):
        return str(self.acao)


class CorDaPeleJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_da_peles')
    cor_da_pele = models.ForeignKey(to='promotor.CorDaPele', on_delete=models.PROTECT,
                                    related_name='cores_da_peles')
    history = HistoricalRecords(table_name='job_cordapelejob_history')


class CorDoCabeloJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_dos_cabelos')
    cor_do_cabelo = models.ForeignKey(to='promotor.CorDoCabelo', on_delete=models.PROTECT,
                                      related_name='cores_dos_cabelos')
    history = HistoricalRecords(table_name='job_cordocabelojob_history')


class CorDosOlhosJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_dos_olhos')
    cor_dos_olhos = models.ForeignKey(to='promotor.CorDosOlhos', on_delete=models.PROTECT,
                                      related_name='cores_dos_olhos')
    history = HistoricalRecords(table_name='job_cordosolhosjob_history')


class DisponibilidadeJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='disponibilidades_jobs')
    datahora_inicio = models.DateTimeField()
    datahora_fim = models.DateTimeField()
    history = HistoricalRecords(table_name='job_disponibilidadejob_history')


class Candidatura(models.Model):
    ATIVA = 1
    RETIRADA = 2
    SELECIONADA_ENTREVISTA = 3
    APROVADA = 4
    REPROVADA = 5
    REPROVADA_ENTREVISTA = 6

    STATUS = (
        (ATIVA, 'Ativa'),
        (RETIRADA, 'Retirada'),
        (SELECIONADA_ENTREVISTA, 'Selecionada para entrevista'),
        (APROVADA, 'Aprovada'),
        (REPROVADA, 'Reprovada'),
        (REPROVADA_ENTREVISTA, 'Reprovada na entrevista'),
    )

    promotor = models.ForeignKey(to='promotor.Promotor', on_delete=models.PROTECT, related_name='candidaturas')
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='candidaturas')
    status = models.PositiveIntegerField(choices=STATUS, default=1)
    observacao = models.CharField(max_length=255, null=True)
    data_hora_status = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords(table_name='job_categoria_history')

templates/candidatos/lista.html
{% extends 'partials/layout.html' %} {% block content %}
    {% load staticfiles %}

    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui two column grid">
                    <div class="column">
                        <h2>
                            <i class="list circle icon"></i>Lista de candidator por job</h2>
                    </div>
                </div>
                <div class="ui divider"></div>
                <div class="ui form ">
                    <form>
                        <div class="fields">
                            <div class="field eight wide ">
                                <label>
                                    Selcione um job
                                </label>
                                <select id="id_job" name="acao" required="">
                                    <option value="" selected="selected">---------</option>
                                    {% for job in job_lista %}
                                        <option value="{{ job.id }}">{{ job.id }} - {{ job.acao }}
                                            - {{ job.tipo }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </form>
                </div>
                <div id="tabela" style="display: none">
                    <table class="ui celled selectable compact table datatable">
                        <thead>
                        <tr>
                            <th class="center aligned six wide">Código</th>
                            <th class="center aligned three wide">Nome</th>
                            <th class="center aligned one wide">Sexo</th>
                            <th class="center aligned one wide">Status</th>
                            <th class="center aligned one wide">Idade</th>
                            <th class="center aligned one wide">Peso</th>
                            <th class="center aligned one wide">Altura</th>
                            <th class="center aligned one wide">Telefone</th>
                            <th class="center aligned three wide no-sort">Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <div id="mensagem">
                    <div class="ui ignored warning message">
                        <b>Selecione um job.</b>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="load" class="ui dimmer">
        <div class="ui text loader">Carregando</div>
    </div>
    <div class="ui small modal" id="modal_fotos">
        <div class="header">Header</div>
        <div class="content">
            <div class="ui medium images">
            </div>
        </div>
        <div class="actions">
            <div class="ui cancel button">Sair</div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://rawgit.com/igorescobar/jQuery-Mask-Plugin/master/dist/jquery.mask.min.js" ></script>
    <script>
        const $id_job = $('#id_job');
        const $tabela = $('#tabela');
        const $mensagem = $('#mensagem');

        let ROW = false;

        $id_job.change(function () {
            CANDIDATOS.get();
        });

        function load(load) {
            if (load) {
                $('#load').addClass('active')
            } else {
                $('#load').removeClass('active')
            }
        }

        const CANDIDATOS = {
            get: () => {
                $mensagem.show();
                $mensagem.find('.ignored').html('<b>Procurando...</b>');
                $tabela.hide();
                if ($id_job.val()) {
                    load(true);
                    $.ajax({
                        url: `${window.location.origin}/api/job/${$id_job.val()}/candidaturas/`,
                        headers: {
                            'Authorization': 'Token {{ user.token }}',
                            'Content-Type': 'application/json'
                        },
                        success: function (candidaturas) {
                            if (candidaturas.length) {
                                let lista = [];
                                for (candidato of candidaturas) {
                                    let btn_selecionar = `<a onclick="CANDIDATOS.status(${candidato.id}, 3)" class="ui icon mini button blue">
                                                            Selecionar para entrevista
                                                        </a>`;
                                    let btn_ativar = `<a onclick="CANDIDATOS.status(${candidato.id}, 1)" class="ui icon mini button green">
                                                            Ativar
                                                        </a>`;
                                    let btn_aprovar = `<a onclick="CANDIDATOS.status(${candidato.id}, 4)" class="ui icon mini button green">
                                                                Aprovar
                                                            </a>`;
                                    let btn_reprovar = `<a onclick="CANDIDATOS.status(${candidato.id}, 5)" class="ui icon mini button red">
                                                                 Reprovar
                                                            </a>`;

                                    let btn_reprovar_entrevista = `<a onclick="CANDIDATOS.status(${candidato.id}, 6)" class="ui icon mini button red">
                                                                 Reprovar na entrevista
                                                            </a>`;

                                    let btn = '';
                                    if (candidato.status == 1) {
                                        if (candidato.job.acao.publico_tem_entrevista) {
                                            btn = btn_selecionar;
                                        }
                                        btn += btn_aprovar + btn_reprovar;
                                    } else if (candidato.status == 3) {
                                        btn = btn_reprovar;
                                        if (candidato.job.acao.publico_tem_entrevista) {
                                            btn += btn_reprovar_entrevista;
                                        }
                                    } else if (candidato.status == 4) {
                                        btn = btn_reprovar;
                                    } else if (candidato.status == 5 || candidato.status == 6) {
                                        btn = btn_ativar
                                    }

                                    lista.push([
                                        `<div data-candidatura='${JSON.stringify(candidato)}' class="right aligned candidatura onclick">${candidato.id}</div>`,
                                        candidato.promotor.nome_exibicao,
                                        candidato.promotor.sexo__display,
                                        candidato.status__display,
                                        `<div class="right aligned">${candidato.idade}</div>`,
                                        `<div class="right aligned">${candidato.promotor.peso}</div>`,
                                        `<div class="right aligned">${candidato.promotor.altura}</div>`,
                                        `<div class="telefone" style="flex-direction:row;display: flex;justify-content: center;">${(candidato.status == 3 || candidato.status == 4) ? candidato.promotor.telefone :
                                            'Indisponível &nbsp' +
                                            '<b data-tooltip="Você só pode ver o telefone de candidatos aprovados.">(?)</b>'} </div>`,
                                        `<div class="center aligned">${btn}</div>`
                                        ,
                                    ]);
                                }
                                $tabela.find('table').DataTable().clear().rows.add(lista).draw();
                                $tabela.show();
                                $mensagem.hide();
                                {#$(".telefone").mask("(00) 0000-00009");#}
                                load(false);
                            } else {
                                load(false);
                                $mensagem.find('.ignored').html('<b>Nenhuma candidatura para esse job.</b>')
                            }
                        },
                        error: function (response) {
                            load(false);
                            toastr.error(response.responseJSON.detail);
                        }
                    })
                } else {
                    $mensagem.find('.ignored').html('<b>Selecione um job.</b>')
                }
            },
            status: (id, status) => {
                ROW = true;
                $.ajax({
                    type: 'POST',
                    url: `${window.location.origin}/api/candidatura/${id}/status/${status}/`,
                    headers: {
                        'Authorization': 'Token {{ user.token }}',
                        'Content-Type': 'application/json'
                    },
                    success: function (success) {
                        CANDIDATOS.get();
                    },
                    error: function (response) {
                        toastr.error(response.responseJSON.error[0])
                    },
                })
            }
        };

        $('table tbody').on('click', 'tr', function () {
            if (ROW){
                ROW = false;
                return;
            }
            let candidatura = $(this).find('.candidatura').attr('data-candidatura');
            candidatura = JSON.parse(candidatura);
            let html = '';
            for (image of candidatura.promotor.imagens) {
                html += `<img src="${image.path}">`;
            }
            let $modal_fotos = $('#modal_fotos');
            $modal_fotos.find('.ui.medium.images').html(html);
            $modal_fotos.find('.header').html(candidatura.promotor.nome_exibicao);
            $modal_fotos.modal('show')
        });
    </script>
{% endblock %}