maisjob/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from apps.agencia.views import AcaoListView, AcaoCreateView, AcaoUpdateView, AcaoDeleteView, \
    AgenciaListView, AgenciaCreateView, AgenciaUpdateView, AgenciaDeleteView
from apps.agencia.viewsets import AgenciaListViewSet
from apps.core.views import HomeView, LogoutView, LoginView
from apps.core.viewsets import EstadoListViewSet
from apps.job.views import JobListView, JobCreateView, JobUpdateView, JobDeleteView, TipoJobListView, TipoJobCreateView, \
    TipoJobUpdateView, TipoJobDeleteView, CandidaturaView, CandidaturaJogoView
from apps.job.viewsets import JobListViewSet, TipoJobViewSet, JobViewSet, CandidaturaViewSet, CandidaturaStatusViewSet
from apps.promotor.views import PromotorCredenciadoListView, PromotorCredenciadoUpdateView
from apps.promotor.viewsets import PromotorCreateViewSet, CorDaPeleListViewSet, CorDoCabeloListViewSet, \
    CorDosOlhosListViewSet, LoginPromotorViewSet, PromotorViewSet, PromotorGetViewSet, PromotorUpdateViewSet, \
    CoresViewSet, ImagemCreateViewSet

router = DefaultRouter()
router.register(r'tipo-job', TipoJobViewSet)
router.register(r'job', JobViewSet)
router.register(r'promotor', PromotorViewSet)
router.register(r'agencia-list', AgenciaListViewSet)
router.register(r'estado-list', EstadoListViewSet)
router.register(r'candidatura', CandidaturaViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/imagem-save/', ImagemCreateViewSet.as_view()),
    url(r'^api/login-promotor/', LoginPromotorViewSet.as_view()),
    url(r'^api/job-list/', JobListViewSet.as_view()),
    url(r'^api/promotor/', PromotorGetViewSet.as_view()),
    url(r'^api/promotor-create/', PromotorCreateViewSet.as_view()),
    url(r'^api/promotor-update/(?P<pk>[0-9]+)/', PromotorUpdateViewSet.as_view()),
    url(r'^api/candidatura/(?P<candidatura>[0-9]+)/status/(?P<status>[0-9]+)/', CandidaturaStatusViewSet.as_view()),
    url(r'^api/cordapele-list/', CorDaPeleListViewSet.as_view()),
    url(r'^api/cordocabelo-list/', CorDoCabeloListViewSet.as_view()),
    url(r'^api/cordosolhos-list/', CorDosOlhosListViewSet.as_view()),
    url(r'^api/cores/', CoresViewSet.as_view()),

    url(regex='^login/$', view=LoginView.as_view(), name='login'),
    url(regex='^logout/$', view=LogoutView.as_view(), name='logout'),
    url(regex='^$', view=HomeView.as_view(), name='home'),

    url(regex='^cadastros/agencia/$', view=AgenciaListView.as_view(), name='cadastros-agencia-list'),
    url(regex='^cadastros/agencia/create$', view=AgenciaCreateView.as_view(), name='cadastros-agencia-create'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/$', view=AgenciaUpdateView.as_view(), name='cadastros-agencia-update'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/delete/$', view=AgenciaDeleteView.as_view(),
        name='cadastros-agencia-delete'),

    url(regex='^cadastros/acao/$', view=AcaoListView.as_view(), name='cadastros-acao-list'),
    url(regex='^cadastros/acao/create$', view=AcaoCreateView.as_view(), name='cadastros-acao-create'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/$', view=AcaoUpdateView.as_view(), name='cadastros-acao-update'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/delete/$', view=AcaoDeleteView.as_view(), name='cadastros-acao-delete'),

    url(regex='^cadastros/tipojob/$', view=TipoJobListView.as_view(), name='cadastros-tipojob-list'),
    url(regex='^cadastros/tipojob/create$', view=TipoJobCreateView.as_view(), name='cadastros-tipojob-create'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/$', view=TipoJobUpdateView.as_view(), name='cadastros-tipojob-update'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/delete/$', view=TipoJobDeleteView.as_view(),
        name='cadastros-tipojob-delete'),

    url(regex='^cadastros/job/$', view=JobListView.as_view(), name='cadastros-job-list'),
    url(regex='^cadastros/job/create$', view=JobCreateView.as_view(), name='cadastros-job-create'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/$', view=JobUpdateView.as_view(), name='cadastros-job-update'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/delete/$', view=JobDeleteView.as_view(), name='cadastros-job-delete'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),

    url(regex='^candidatura/list/$', view=CandidaturaView.as_view(), name='candidatura-list'),
    url(regex='^candidatura/jogo/$', view=CandidaturaJogoView.as_view(), name='candidatura-jogo'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),
]

if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

apps/agencia/models.py
from django.db import models

# Create your models here.
from simple_history.models import HistoricalRecords
from hashids import Hashids
from random import randint


class Agencia(models.Model):
    FISICA = 1
    JURIDICA = 2

    PESSOA = (
        (FISICA, 'Pessoa física'),
        (JURIDICA, 'Pessoa jurídica')
    )
    codigo_indicacao = models.CharField(max_length=8, unique=True, null=True)
    cpf_cnpj = models.CharField(max_length=18, unique=True)
    tipo_pessoa = models.PositiveIntegerField(choices=PESSOA)
    nome_exibicao = models.CharField(max_length=255)
    nome_razao_social = models.CharField(max_length=255)
    contato = models.CharField(max_length=255)
    telefone = models.CharField(max_length=255)
    email = models.EmailField()
    datahora_inclusao = models.DateTimeField(auto_now_add=True)
    datahora_alteracao = models.DateTimeField(auto_now=True)

    history = HistoricalRecords(table_name='agencia_agencia_history')

    def __str__(self):
        return self.nome_exibicao

    def save(self, *args, **kwargs):
        if self.id:
            return super(Agencia, self).save(*args, **kwargs)
        try:
            new_numero = Agencia.objects.latest('id').id + 1
        except Agencia.DoesNotExist:
            new_numero = 1
        self.codigo_indicacao = (Hashids(salt='nova_agencia', min_length=8).encrypt(new_numero + randint(0, 9999))).lower()
        return super(Agencia, self).save(*args, **kwargs)


class Acao(models.Model):
    agencia = models.ForeignKey(to='Agencia', on_delete=models.PROTECT, related_name='acoes')
    cidade = models.ForeignKey(to='core.Cidade', on_delete=models.PROTECT, related_name='acoes', null=True)
    datahora_inicio_exibicao = models.DateTimeField()
    datahora_fim_exibicao = models.DateTimeField()
    datahora_inicio_acao = models.DateTimeField()
    datahora_fim_acao = models.DateTimeField()
    publico_titulo = models.CharField(max_length=255)
    publico_descricao = models.CharField(max_length=255, null=True)
    publico_local = models.CharField(max_length=255, null=True)
    publico_tem_entrevista = models.BooleanField(default=False)
    publico_local_entrevista = models.CharField(max_length=255, null=True)
    publico_data_hora_entrevista = models.CharField(max_length=255, null=True)

    history = HistoricalRecords(table_name='agencia_acao_history')

    def __str__(self):
        return self.publico_titulo


class Cliente(models.Model):
    FISICA = 1
    JURIDICA = 2

    PESSOA = (
        (FISICA, 'Pessoa física'),
        (JURIDICA, 'Pessoa jurídica')
    )

    agencia = models.ForeignKey(to='Agencia', on_delete=models.PROTECT, related_name='clientes')
    cpf_cnpj = models.CharField(max_length=18, unique=True)
    tipo_pessoa = models.PositiveIntegerField(choices=PESSOA)
    nome_exibicao = models.CharField(max_length=255)
    nome_razao_social = models.CharField(max_length=255)
    contato = models.CharField(max_length=255)
    telefone = models.CharField(max_length=255)
    email = models.EmailField()

    history = HistoricalRecords(table_name='agencia_cliente_history')

apps/agencia/forms.py
from datetime import datetime

from django import forms

from apps.core.models import Cidade
from .models import Acao, Agencia


class AcaoForm(forms.ModelForm):
    class Meta:
        model = Acao
        fields = ('agencia', 'cidade', 'datahora_inicio_exibicao', 'datahora_fim_exibicao', 'datahora_inicio_acao',
                  'datahora_fim_acao', 'publico_titulo', 'publico_descricao', 'publico_local', 'publico_tem_entrevista',
                  'publico_local_entrevista', 'publico_data_hora_entrevista',)

    def __init__(self, *args, **kwargs):
        super(AcaoForm, self).__init__(*args, **kwargs)
        self.fields['publico_data_hora_entrevista'].required = False
        self.fields['publico_local_entrevista'].required = False
        self.fields['publico_descricao'].required = False

    def clean_datahora_inicio_acao(self):
        data = self.data

        inicio = data.get('datahora_inicio_acao')
        fim_exibicao = data.get('datahora_fim_exibicao')

        if len(inicio) == 19:
            inicio = datetime.strptime(inicio, '%d/%m/%Y  %H:%M:%S')
        else:
            inicio = datetime.strptime(inicio, '%d/%m/%Y  %H:%M')

        if len(fim_exibicao) == 19:
            fim_exibicao = datetime.strptime(fim_exibicao, '%d/%m/%Y  %H:%M:%S')
        else:
            fim_exibicao = datetime.strptime(fim_exibicao, '%d/%m/%Y  %H:%M')

        fim = data.get('datahora_fim_acao')

        if len(fim) == 19:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M:%S')
        else:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M')

        if inicio < fim_exibicao:
            frase = 'A data e hora do início da AÇÃO deve ser POSTERIOR à data e hora do fim da exibição.'
            raise forms.ValidationError(frase)

        return inicio

    def clean_datahora_fim_exibicao(self):
        data = self.data

        inicio = data.get('datahora_inicio_exibicao')

        if len(inicio) == 19:
            inicio = datetime.strptime(inicio, '%d/%m/%Y  %H:%M:%S')
        else:
            inicio = datetime.strptime(inicio, '%d/%m/%Y  %H:%M')

        fim = data.get('datahora_fim_exibicao')

        if len(fim) == 19:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M:%S')
        else:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M')

        if inicio > fim:
            frase = 'A data e hora do fim da exibição devem ser POSTERIORES a data e hora do início da exibição.'
            raise forms.ValidationError(frase)

        return inicio

    def clean_datahora_inicio_exibicao(self):
        data = self.data

        inicio = datetime.now()
        fim = data.get('datahora_inicio_exibicao')

        if len(fim) == 19:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M:%S')
        else:
            fim = datetime.strptime(fim, '%d/%m/%Y  %H:%M')

        if inicio > fim:
            frase = 'A data e hora do início da exibição deve ser POSTERIOR à data e hora ATUAIS.'
            raise forms.ValidationError(frase)

        return inicio

    def clean_publico_data_hora_entrevista(self):
        data = self.data

        if data.get('publico_tem_entrevista') and not data.get('publico_data_hora_entrevista'):
            raise forms.ValidationError('Esse campo é obrigatório quando tem entrevista.')

        inicio = data.get('publico_data_hora_entrevista')

        if inicio:
            fim_exibicao = data.get('datahora_fim_exibicao')

            if inicio < fim_exibicao:
                frase = 'A data e hora da entrevista deve ser POSTERIOR à data e hora do fim da exibição.'
                raise forms.ValidationError(frase)

        return data.get('publico_data_hora_entrevista')


class AgenciaForm(forms.ModelForm):
    class Meta:
        model = Agencia
        fields = ('cpf_cnpj', 'tipo_pessoa', 'nome_exibicao', 'nome_razao_social', 'contato',
                  'telefone', 'email')

apps/agencia/views.py
from django.db.models import Count, Q
from django.db.models.functions import Coalesce
from django.shortcuts import render

# Create your views here.
from django.core.paginator import Paginator
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.api.permissions import SuperUserRequiredMixin
from .models import Acao, Agencia
from .forms import AcaoForm, AgenciaForm


class AcaoListView(LoginRequiredMixin, ListView):
    model = Acao
    template_name = 'cadastros/acao/lista.html'
    context_object_name = "acao_lista"


class AcaoCreateView(LoginRequiredMixin, CreateView):
    model = Acao
    template_name = 'cadastros/acao/form.html'
    form_class = AcaoForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-acao-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-acao-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class AcaoUpdateView(LoginRequiredMixin, UpdateView):
    model = Acao
    template_name = 'cadastros/acao/form.html'
    form_class = AcaoForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-acao-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-acao-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class AcaoDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            obj = get_object_or_404(Acao, pk=pk)
            obj.delete()
            messages.success(request, 'Excluído(a) com sucesso')
        except:
            messages.error(request, 'Não foi possível excluir')
        return HttpResponseRedirect(reverse('cadastros-acao-list'))


class AgenciaListView(SuperUserRequiredMixin, LoginRequiredMixin, ListView):
    model = Agencia
    template_name = 'cadastros/agencia/lista.html'
    context_object_name = "agencia_lista"


class AgenciaCreateView(SuperUserRequiredMixin, LoginRequiredMixin, CreateView):
    model = Agencia
    template_name = 'cadastros/agencia/form.html'
    form_class = AgenciaForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-agencia-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-agencia-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class AgenciaUpdateView(SuperUserRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Agencia
    template_name = 'cadastros/agencia/form.html'
    form_class = AgenciaForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-agencia-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-agencia-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class AgenciaDeleteView(SuperUserRequiredMixin, LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            obj = get_object_or_404(Agencia, pk=pk)
            obj.delete()
            messages.success(request, 'Excluído(a) com sucesso')
        except:
            messages.error(request, 'Não foi possível excluir')
        return HttpResponseRedirect(reverse('cadastros-agencia-list'))

templates/cadastros/agencia/form.html
{% extends 'partials/layout.html' %} {% block content %}
    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui one column grid">
                    <div class="column">
                        <h2>
                            <i class="add circle icon"></i>Formulário de agência</h2>
                    </div>
                </div>
                <div class="ui divider"></div>
            </div>
            <div class="column">
                <div class="ui form {% if form.errors %}error{% endif %}">
                    {{ form.non_field_errors }} {% if form.errors %}
                    <div class="ui error message">
                        <p>
                            {% if form.errors|length == 1 %} Por favor, corrija o erro abaixo. {% else %} Por favor,
                                corrija
                                os erros abaixo. {% endif %}
                        </p>
                    </div>
                {% endif %}
                    <form method="post" id="form" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}
                        {% for field in form.hidden_fields %} {{ field }} {% endfor %}
                        <div class="column">
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.cpf_cnpj label="CPF/CNPJ" class="eight wide" %}
                                {% include 'partials/form_field.html' with field=form.tipo_pessoa class="eight wide" %}
                                {% include 'partials/form_field.html' with field=form.nome_exibicao class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.nome_razao_social class="eight wide" %}
                                {% include 'partials/form_field.html' with field=form.contato class="eight wide" %}
                                {% include 'partials/form_field.html' with field=form.telefone class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.email class="eight wide" %}
                            </div>
                        </div>
                        <button type="submit" name="outro" class="ui labeled icon button teal right floated">
                            <i class="save icon"></i>
                            Salvar e cadastrar outro
                        </button>
                        <button type="submit" class="ui labeled icon button teal right floated">
                            <i class="save icon"></i>
                            Salvar
                        </button>
                        <a href="{% url 'cadastros-agencia-list' %}" class="ui labeled icon button black right floated">
                            <i class="cancel icon"></i>
                            Cancelar
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        let $tem_entrevista = $('.tem_entrevista');
        let $id_publico_tem_entrevista = $('#id_publico_tem_entrevista');
        let funcao = () => {
            if ($id_publico_tem_entrevista.is(":checked")) {
                $tem_entrevista.find('input').attr('readonly', false);
                $tem_entrevista.find('select').attr('disabled', false);
                $('#id_publico_data_hora_entrevista').addClass('datetime');
                DATETIME();
                $tem_entrevista.addClass('required');
            } else {
                $tem_entrevista.find('input').attr('readonly', true);
                $tem_entrevista.find('select').attr('disabled', true);
                $('#id_publico_data_hora_entrevista').removeClass('datetime');
                $tem_entrevista.find('input').val('');
                $tem_entrevista.removeClass('required');
            }
        };
        funcao();
        $id_publico_tem_entrevista.change(function () {
            funcao();
        });
        $tem_entrevista.find('input').click(function () {
            if (!$id_publico_tem_entrevista.is(":checked")) {
                toastr.error('É necessário marcar que tem entrevista.')
            }
        });
    </script>
{% endblock %}

templates/cadastros/agencia/lista.html
{% extends 'partials/layout.html' %} {% block content %}
    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui two column grid">
                    <div class="column">
                        <h2>
                            <i class="list circle icon"></i>Lista de agência</h2>
                    </div>
                    <div class="column">
                        <a href="{% url 'cadastros-agencia-create' %}"
                           class="ui labeled right floated icon button">
                            <i class="plus icon"></i>
                            Nova agência
                        </a>
                    </div>
                </div>
                <div class="ui divider"></div>
                <table class="ui celled selectable compact table">
                    <thead>
                    <tr>
                        <th class="center aligned one wide">Código Indicação</th>
                        <th class="center aligned two wide">CPF/CNPJ</th>
                        <th class="center aligned two wide">Tipo Pessoa</th>
                        <th class="center aligned one wide">Nome Exibição</th>
                        <th class="center aligned one wide">Nome Razão Social</th>
                        <th class="center aligned one wide">Contato</th>
                        <th class="center aligned one wide">Telefone</th>
                        <th class="center aligned two wide">E-mail</th>
                        <th class="center aligned two wide no-sort">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if agencia_lista %}
                        {% for agencia in agencia_lista %}
                            <tr>
                                <td>{{ agencia.codigo_indicacao }}</td>
                                <td>{{ agencia.cpf_cnpj }}</td>
                                <td>{{ agencia.tipo_pessoa }}</td>
                                <td>{{ agencia.nome_exibicao }}</td>
                                <td>{{ agencia.nome_razao_social }}</td>
                                <td>{{ agencia.contato }}</td>
                                <td>{{ agencia.telefone }}</td>
                                <td>{{ agencia.email }}</td>
                                <td class="center aligned">
                                    <a href="{% url 'cadastros-agencia-update' agencia.id %}"
                                       class="ui icon tiny button green">
                                        <i class="edit icon"></i>
                                    </a>
                                    <a class="ui icon tiny button red"
                                       onclick="MODAL_APAGAR('Confirma a exclusão de agência?', '{% url 'cadastros-agencia-delete' agencia.id %}')">
                                        <i class="trash icon"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="10">
                                <div class="ui ignored warning message">
                                    <b>Nenhuma agência cadastrada.</b>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{% endblock %}