maisjob/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from apps.agencia.views import AcaoListView, AcaoCreateView, AcaoUpdateView, AcaoDeleteView, \
    AgenciaListView, AgenciaCreateView, AgenciaUpdateView, AgenciaDeleteView
from apps.agencia.viewsets import AgenciaListViewSet
from apps.core.views import HomeView, LogoutView, LoginView
from apps.core.viewsets import EstadoListViewSet
from apps.job.views import JobListView, JobCreateView, JobUpdateView, JobDeleteView, TipoJobListView, TipoJobCreateView, \
    TipoJobUpdateView, TipoJobDeleteView, CandidaturaView, CandidaturaJogoView
from apps.job.viewsets import JobListViewSet, TipoJobViewSet, JobViewSet, CandidaturaViewSet, CandidaturaStatusViewSet
from apps.promotor.views import PromotorCredenciadoListView, PromotorCredenciadoUpdateView
from apps.promotor.viewsets import PromotorCreateViewSet, CorDaPeleListViewSet, CorDoCabeloListViewSet, \
    CorDosOlhosListViewSet, LoginPromotorViewSet, PromotorViewSet, PromotorGetViewSet, PromotorUpdateViewSet, \
    CoresViewSet, ImagemCreateViewSet

router = DefaultRouter()
router.register(r'tipo-job', TipoJobViewSet)
router.register(r'job', JobViewSet)
router.register(r'promotor', PromotorViewSet)
router.register(r'agencia-list', AgenciaListViewSet)
router.register(r'estado-list', EstadoListViewSet)
router.register(r'candidatura', CandidaturaViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/imagem-save/', ImagemCreateViewSet.as_view()),
    url(r'^api/login-promotor/', LoginPromotorViewSet.as_view()),
    url(r'^api/job-list/', JobListViewSet.as_view()),
    url(r'^api/promotor/', PromotorGetViewSet.as_view()),
    url(r'^api/promotor-create/', PromotorCreateViewSet.as_view()),
    url(r'^api/promotor-update/(?P<pk>[0-9]+)/', PromotorUpdateViewSet.as_view()),
    url(r'^api/candidatura/(?P<candidatura>[0-9]+)/status/(?P<status>[0-9]+)/', CandidaturaStatusViewSet.as_view()),
    url(r'^api/cordapele-list/', CorDaPeleListViewSet.as_view()),
    url(r'^api/cordocabelo-list/', CorDoCabeloListViewSet.as_view()),
    url(r'^api/cordosolhos-list/', CorDosOlhosListViewSet.as_view()),
    url(r'^api/cores/', CoresViewSet.as_view()),

    url(regex='^login/$', view=LoginView.as_view(), name='login'),
    url(regex='^logout/$', view=LogoutView.as_view(), name='logout'),
    url(regex='^$', view=HomeView.as_view(), name='home'),

    url(regex='^cadastros/agencia/$', view=AgenciaListView.as_view(), name='cadastros-agencia-list'),
    url(regex='^cadastros/agencia/create$', view=AgenciaCreateView.as_view(), name='cadastros-agencia-create'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/$', view=AgenciaUpdateView.as_view(), name='cadastros-agencia-update'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/delete/$', view=AgenciaDeleteView.as_view(),
        name='cadastros-agencia-delete'),

    url(regex='^cadastros/acao/$', view=AcaoListView.as_view(), name='cadastros-acao-list'),
    url(regex='^cadastros/acao/create$', view=AcaoCreateView.as_view(), name='cadastros-acao-create'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/$', view=AcaoUpdateView.as_view(), name='cadastros-acao-update'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/delete/$', view=AcaoDeleteView.as_view(), name='cadastros-acao-delete'),

    url(regex='^cadastros/tipojob/$', view=TipoJobListView.as_view(), name='cadastros-tipojob-list'),
    url(regex='^cadastros/tipojob/create$', view=TipoJobCreateView.as_view(), name='cadastros-tipojob-create'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/$', view=TipoJobUpdateView.as_view(), name='cadastros-tipojob-update'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/delete/$', view=TipoJobDeleteView.as_view(),
        name='cadastros-tipojob-delete'),

    url(regex='^cadastros/job/$', view=JobListView.as_view(), name='cadastros-job-list'),
    url(regex='^cadastros/job/create$', view=JobCreateView.as_view(), name='cadastros-job-create'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/$', view=JobUpdateView.as_view(), name='cadastros-job-update'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/delete/$', view=JobDeleteView.as_view(), name='cadastros-job-delete'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),

    url(regex='^candidatura/list/$', view=CandidaturaView.as_view(), name='candidatura-list'),
    url(regex='^candidatura/jogo/$', view=CandidaturaJogoView.as_view(), name='candidatura-jogo'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),
]

if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

apps/promotor/models.py
import base64
from datetime import date

import os
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import models
from unicodedata import normalize

# Create your models here.
from simple_history.models import HistoricalRecords
from hashids import Hashids
from random import randint


class Promotor(models.Model):
    PREFIRO_NAO_DIZER = 1
    MASCULINO = 2
    FEMININO = 3

    SEXO = (
        (PREFIRO_NAO_DIZER, 'Prefiro não dizer'),
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )

    CADASTRADO = 0
    CREDENCIADO = 1

    STATUS = (
        (CADASTRADO, 'Cadastrado'),
        (CREDENCIADO, 'Credenciado'),
    )

    codigoindicacao = models.CharField(max_length=8, unique=True, null=True)
    status = models.PositiveIntegerField(choices=STATUS, default=0)
    usuario = models.OneToOneField(to='core.Usuario', related_name='promotor', on_delete=models.PROTECT)
    nome_exibicao = models.CharField(max_length=255, )
    nome_completo = models.CharField(max_length=255, )
    cpf = models.CharField(max_length=15)
    data_nascimento = models.DateField()
    sexo = models.PositiveIntegerField(choices=SEXO)
    peso = models.FloatField()
    altura = models.IntegerField()
    cor_da_pele = models.ForeignKey(to='CorDaPele', on_delete=models.PROTECT, related_name='promotores')
    cor_do_cabelo = models.ForeignKey(to='CorDoCabelo', on_delete=models.PROTECT, related_name='promotores')
    cor_dos_olhos = models.ForeignKey(to='CorDosOlhos', on_delete=models.PROTECT, related_name='promotores')
    cidade = models.ForeignKey(to='core.Cidade', on_delete=models.PROTECT, related_name='promotores')
    telefone = models.CharField(max_length=255)

    def __str__(self):
        return self.nome_exibicao

    def idade(self):
        today = date.today()
        data_nascimento = self.data_nascimento
        idade = today.year - data_nascimento.year - (
            (today.month, today.day) < (data_nascimento.month, data_nascimento.day))
        return idade

    def cpf_mascara(self):
        cpf = self.cpf
        return '{}.{}.{}-{}'.format(cpf[:3], cpf[3:6], cpf[6:9], cpf[9:])

    def credenciar(self, *args, **kwargs):
        try:
            new_numero = Promotor.objects.latest('id').id + 1
        except Promotor.DoesNotExist:
            new_numero = 1
        new_numero = new_numero + randint(0, 9999)
        hash = Hashids(salt='novo_promotor', min_length=8).encrypt(new_numero)

        self.codigoindicacao = hash.lower()
        self.save()
        return True

    def job_para_min(self, job):
        cores_dos_olhos = [o.cor_dos_olhos_id for o in job.cores_dos_olhos.all()]
        cores_da_peles = [o.cor_da_pele_id for o in job.cores_da_peles.all()]
        cores_dos_cabelos = [o.cor_do_cabelo_id for o in job.cores_dos_cabelos.all()]
        arrayValidacao = [True, True, True, True, True, True, True, True]

        if job.perfil_sexo:
            if not job.perfil_sexo == 1:
                if not self.sexo == job.perfil_sexo:
                    arrayValidacao[0] = False

        if cores_dos_olhos:
            if not self.cor_dos_olhos_id in cores_dos_olhos:
                arrayValidacao[1] = False

        if cores_da_peles:
            if not self.cor_da_pele_id in cores_da_peles:
                arrayValidacao[2] = False

        if cores_dos_cabelos:
            if not self.cor_do_cabelo_id in cores_dos_cabelos:
                arrayValidacao[3] = False

        if job.perfil_altura_minima:
            if not self.altura >= job.perfil_altura_minima:
                arrayValidacao[4] = False

        if job.perfil_altura_maxima:
            if not self.altura <= job.perfil_altura_maxima:
                arrayValidacao[5] = False

        if job.perfil_idade_minima:
            if not self.idade() >= job.perfil_idade_minima:
                arrayValidacao[6] = False

        if job.perfil_idade_maxima:
            if not self.idade() <= job.perfil_idade_maxima:
                arrayValidacao[7] = False

        for validacao in arrayValidacao:
            if validacao == False:
                return False

        return True

    history = HistoricalRecords(table_name='promotor_promotor_history')


class PromotorCredenciado(models.Model):
    promotor = models.OneToOneField(to='Promotor', related_name='credenciamento', on_delete=models.PROTECT)
    data_pagamento = models.DateField(null=True)
    valor_pago = models.FloatField(null=True)
    promotor_indicacao = models.ForeignKey(to='Promotor', related_name='credenciamentos_indicados',
                                           on_delete=models.PROTECT, null=True)
    agencia_indicacao = models.ForeignKey(to='agencia.Agencia', related_name='credenciamentos_indicados',
                                          on_delete=models.PROTECT, null=True)

    history = HistoricalRecords(table_name='promotor_promotorcredenciado_history')

    def valor_pago_formatado(self):
        return "{0:.2f}".format(self.valor_pago)


class CorDaPele(models.Model):
    descricao = models.CharField(max_length=255)

    history = HistoricalRecords(table_name='promotor_cordapele_history')

    def __str__(self):
        return self.descricao


class CorDoCabelo(models.Model):
    descricao = models.CharField(max_length=255)

    history = HistoricalRecords(table_name='promotor_cordocabelo_history')

    def __str__(self):
        return self.descricao


class CorDosOlhos(models.Model):
    descricao = models.CharField(max_length=255)

    history = HistoricalRecords(table_name='promotor_cordosolhos_history')

    def __str__(self):
        return self.descricao


class Imagem(models.Model):
    FRENTE = 1
    PERFIL = 2
    COSTAS = 3
    OUTRAS = 4

    TIPO = (
        (FRENTE, 'Frente'),
        (PERFIL, 'Perfil'),
        (COSTAS, 'Costas'),
        (OUTRAS, 'Outros'),
    )

    path = models.ImageField(upload_to='imagem')
    tipo = models.PositiveIntegerField(choices=TIPO)
    promotor = models.ForeignKey(to='Promotor', on_delete=models.PROTECT, related_name='imagens', null=True)
    acao = models.ForeignKey(to='agencia.Acao', on_delete=models.PROTECT, related_name='imagens', null=True)

    history = HistoricalRecords(table_name='promotor_imagem_history')

    def deletar_arquivo(self):
        if self.id:
            try:
                nome = str(self.path).replace('imagem/', '')
                nome = nome.replace('imagem\\', '')
                local = os.path.join(settings.BASE_DIR, 'media', 'imagem', nome)
                os.remove(local)
            except OSError:
                pass

            self.delete()

            return True
        return False

    def salvar64(self, path64):
        if self.id:
            try:
                nome = normalize('NFKD', self.promotor.nome_exibicao).encode('ASCII', 'ignore').decode('ASCII')
            except:
                nome = 'erro_no_nome'

            format, imgstr = path64.split(';base64,')
            ext = format.split('/')[-1]
            data = ContentFile(base64.b64decode(imgstr))
            file_name = nome.replace(" ", "_") + "." + ext

            self.path.save(str(self.id) + '_' + file_name, data, save=True)
            return True
        return False

templates/cadastros/credenciamento/form.html
{% extends 'partials/layout.html' %} {% block content %}
    {% load widget_tweaks %}

    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui one column grid">
                    <div class="column">
                        <h2>
                            <i class="add circle icon"></i>Credenciamento</h2>
                    </div>
                </div>
                <div class="ui divider"></div>
            </div>
            <div class="column">
                <div class="ui form {% if form.errors %}error{% endif %}">
                    {{ form.non_field_errors }} {% if form.errors %}
                    <div class="ui error message">
                        <p>
                            {% if form.errors|length == 1 %} Por favor, corrija o erro abaixo. {% else %} Por favor,
                                corrija
                                os erros abaixo. {% endif %}
                        </p>
                    </div>
                {% endif %}
                    <form method="post" id="form" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}
                        {% for field in form.hidden_fields %} {{ field }} {% endfor %}
                        <div class="column">
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.data_pagamento|attr:"rel:date" class="four wide" %}
                                {% include 'partials/form_field.html' with field=form.valor_pago class="four wide" %}
                            </div>
                        </div>
                        <button onclick="enviar();" type="button" class="ui labeled icon button teal right floated">
                            <i class="save icon"></i>
                            Salvar
                        </button>
                        <a href="{% url 'cadastros-credenciamento-list' %}"
                           class="ui labeled icon button black right floated">
                            <i class="cancel icon"></i>
                            Cancelar
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div id="modal_mensagem" class="ui tiny modal">
        <div class="header">Tem certeza que deseja credenciar como cortesia?</div>
        <div class="actions">
            <div class="ui negative button">Não</div>
            <div class="ui positive right labeled icon button">Confirmar <i class="checkmark icon"></i></div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        const enviar = () => {
            if ($('#id_valor_pago').val() == '0') {
                mensagem();
            } else {
                $('#form').submit();
            }
        };

        function mensagem() {
            let modal = $('#modal_mensagem');
            modal.modal({
                closable: false,
                onApprove: function () {
                    $('#form').submit();
                }
            }).modal('show');
        }
    </script>
{% endblock %}

templates/cadastros/credenciamento/lista.html
{% extends 'partials/layout.html' %} {% block content %}
    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui two column grid">
                    <div class="column">
                        <h2>
                            <i class="list circle icon"></i>Lista de promotores credenciados</h2>
                    </div>
                </div>
                <div class="ui divider"></div>
                <table class="ui celled selectable compact table datatable">
                    <thead>
                    <tr>
                        <th class="center aligned one wide">CPF</th>
                        <th class="center aligned two wide">Promotor</th>
                        <th class="center aligned one wide">Código indicação</th>
                        <th class="center aligned two wide">Indicado por</th>
                        <th class="center aligned two wide">Valor pago</th>
                        <th class="center aligned one wide">Data pagamento</th>
                        <th class="center aligned one wide no-sort">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if credenciamento_lista %}
                        {% for promo_crede in credenciamento_lista %}
                            <tr>
                                <td>{{ promo_crede.promotor.cpf_mascara }}</td>
                                <td>{{ promo_crede.promotor }}</td>
                                <td>
                                    {% if promo_crede.promotor.codigoindicacao %}
                                        {{ promo_crede.promotor.codigoindicacao }}
                                    {% else %}
                                        Sem indicação.
                                    {% endif %}
                                </td>
                                <td>
                                    {% if promo_crede.agencia_indicacao %}
                                        {{ promo_crede.agencia_indicacao.codigo_indicacao }} -
                                        {{ promo_crede.agencia_indicacao }}
                                    {% endif %}
                                    {% if promo_crede.promotor_indicacao %}
                                        {{ promo_crede.promotor_indicacao.codigoindicacao }} -
                                        {{ promo_crede.promotor_indicacao }}
                                    {% endif %}
                                    {% if not promo_crede.promotor_indicacao and not promo_crede.agencia_indicacao %}
                                        Sem indicação.
                                    {% endif %}
                                </td>
                                <td>
                                    {% if promo_crede.valor_pago %}
                                        <span style="float: right;">
                                        R$ {{ promo_crede.valor_pago_formatado }}
                                    </span>
                                    {% else %}
                                        {% if promo_crede.valor_pago  ==  0 %}
                                            Cortesia
                                        {% else %}
                                            Não foi pago.
                                        {% endif %}
                                    {% endif %}
                                </td>
                                <td>{{ promo_crede.data_pagamento | date:'d/m/Y' }}</td>
                                <td class="center aligned">
                                    <a href="{% url 'cadastros-credenciamento-update' promo_crede.id %}"
                                       class="ui icon tiny button green">Credenciar
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="10">
                                <div class="ui ignored warning message">
                                    <b>Nenhuma ação cadastrada.</b>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{% endblock %}