maisjob/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from apps.agencia.views import AcaoListView, AcaoCreateView, AcaoUpdateView, AcaoDeleteView, \
    AgenciaListView, AgenciaCreateView, AgenciaUpdateView, AgenciaDeleteView
from apps.agencia.viewsets import AgenciaListViewSet
from apps.core.views import HomeView, LogoutView, LoginView
from apps.core.viewsets import EstadoListViewSet
from apps.job.views import JobListView, JobCreateView, JobUpdateView, JobDeleteView, TipoJobListView, TipoJobCreateView, \
    TipoJobUpdateView, TipoJobDeleteView, CandidaturaView, CandidaturaJogoView
from apps.job.viewsets import JobListViewSet, TipoJobViewSet, JobViewSet, CandidaturaViewSet, CandidaturaStatusViewSet
from apps.promotor.views import PromotorCredenciadoListView, PromotorCredenciadoUpdateView
from apps.promotor.viewsets import PromotorCreateViewSet, CorDaPeleListViewSet, CorDoCabeloListViewSet, \
    CorDosOlhosListViewSet, LoginPromotorViewSet, PromotorViewSet, PromotorGetViewSet, PromotorUpdateViewSet, \
    CoresViewSet, ImagemCreateViewSet

router = DefaultRouter()
router.register(r'tipo-job', TipoJobViewSet)
router.register(r'job', JobViewSet)
router.register(r'promotor', PromotorViewSet)
router.register(r'agencia-list', AgenciaListViewSet)
router.register(r'estado-list', EstadoListViewSet)
router.register(r'candidatura', CandidaturaViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/imagem-save/', ImagemCreateViewSet.as_view()),
    url(r'^api/login-promotor/', LoginPromotorViewSet.as_view()),
    url(r'^api/job-list/', JobListViewSet.as_view()),
    url(r'^api/promotor/', PromotorGetViewSet.as_view()),
    url(r'^api/promotor-create/', PromotorCreateViewSet.as_view()),
    url(r'^api/promotor-update/(?P<pk>[0-9]+)/', PromotorUpdateViewSet.as_view()),
    url(r'^api/candidatura/(?P<candidatura>[0-9]+)/status/(?P<status>[0-9]+)/', CandidaturaStatusViewSet.as_view()),
    url(r'^api/cordapele-list/', CorDaPeleListViewSet.as_view()),
    url(r'^api/cordocabelo-list/', CorDoCabeloListViewSet.as_view()),
    url(r'^api/cordosolhos-list/', CorDosOlhosListViewSet.as_view()),
    url(r'^api/cores/', CoresViewSet.as_view()),

    url(regex='^login/$', view=LoginView.as_view(), name='login'),
    url(regex='^logout/$', view=LogoutView.as_view(), name='logout'),
    url(regex='^$', view=HomeView.as_view(), name='home'),

    url(regex='^cadastros/agencia/$', view=AgenciaListView.as_view(), name='cadastros-agencia-list'),
    url(regex='^cadastros/agencia/create$', view=AgenciaCreateView.as_view(), name='cadastros-agencia-create'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/$', view=AgenciaUpdateView.as_view(), name='cadastros-agencia-update'),
    url(regex='^cadastros/agencia/(?P<pk>[0-9]+)/delete/$', view=AgenciaDeleteView.as_view(),
        name='cadastros-agencia-delete'),

    url(regex='^cadastros/acao/$', view=AcaoListView.as_view(), name='cadastros-acao-list'),
    url(regex='^cadastros/acao/create$', view=AcaoCreateView.as_view(), name='cadastros-acao-create'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/$', view=AcaoUpdateView.as_view(), name='cadastros-acao-update'),
    url(regex='^cadastros/acao/(?P<pk>[0-9]+)/delete/$', view=AcaoDeleteView.as_view(), name='cadastros-acao-delete'),

    url(regex='^cadastros/tipojob/$', view=TipoJobListView.as_view(), name='cadastros-tipojob-list'),
    url(regex='^cadastros/tipojob/create$', view=TipoJobCreateView.as_view(), name='cadastros-tipojob-create'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/$', view=TipoJobUpdateView.as_view(), name='cadastros-tipojob-update'),
    url(regex='^cadastros/tipojob/(?P<pk>[0-9]+)/delete/$', view=TipoJobDeleteView.as_view(),
        name='cadastros-tipojob-delete'),

    url(regex='^cadastros/job/$', view=JobListView.as_view(), name='cadastros-job-list'),
    url(regex='^cadastros/job/create$', view=JobCreateView.as_view(), name='cadastros-job-create'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/$', view=JobUpdateView.as_view(), name='cadastros-job-update'),
    url(regex='^cadastros/job/(?P<pk>[0-9]+)/delete/$', view=JobDeleteView.as_view(), name='cadastros-job-delete'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),

    url(regex='^candidatura/list/$', view=CandidaturaView.as_view(), name='candidatura-list'),
    url(regex='^candidatura/jogo/$', view=CandidaturaJogoView.as_view(), name='candidatura-jogo'),

    url(regex='^cadastros/credenciamento/$', view=PromotorCredenciadoListView.as_view(),
        name='cadastros-credenciamento-list'),
    url(regex='^cadastros/credenciamento/(?P<pk>[0-9]+)/$', view=PromotorCredenciadoUpdateView.as_view(),
        name='cadastros-credenciamento-update'),
]

if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

apps/job/models.py
from django.db import models

# Create your models here.
from simple_history.models import HistoricalRecords


class TipoJob(models.Model):
    HORA = 1
    DIARIA = 2
    SEMANA = 3
    MES = 4

    MODOS_PAGAMENTOS = (
        (HORA, 'Pagamento por hora'),
        (DIARIA, 'Pagamento por dia'),
        (SEMANA, 'Pagamento por semana'),
        (MES, 'Pagamento por mês')
    )

    descricao = models.CharField(max_length=255)
    modo_pagamento_sugerido = models.PositiveIntegerField(choices=MODOS_PAGAMENTOS)
    history = HistoricalRecords(table_name='job_tipojob_history')

    def __str__(self):
        return self.descricao


class Job(models.Model):
    PREFIRO_NAO_DIZER = 1
    MASCULINO = 2
    FEMININO = 3

    SEXO = (
        (PREFIRO_NAO_DIZER, 'Prefiro não dizer'),
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )

    acao = models.ForeignKey(to='agencia.Acao', on_delete=models.PROTECT, related_name='jobs')
    tipo = models.ForeignKey(to='TipoJob', on_delete=models.PROTECT, related_name='jobs')
    modo_pagamento = models.PositiveIntegerField(choices=TipoJob.MODOS_PAGAMENTOS)
    quantidade_vagas_totais = models.IntegerField()
    quantidade_vagas_disponiveis = models.IntegerField()
    quantidade_de_modo_pagamento = models.IntegerField()
    cache_por_modo_pagamento = models.FloatField()
    cache_individual = models.FloatField()
    cache_total = models.FloatField()
    observacao = models.CharField(max_length=255, null=True)

    perfil_sexo = models.PositiveIntegerField(choices=SEXO, null=True)
    perfil_idade_minima = models.IntegerField(null=True)
    perfil_idade_maxima = models.IntegerField(null=True)
    perfil_altura_minima = models.FloatField(null=True)
    perfil_altura_maxima = models.FloatField(null=True)

    history = HistoricalRecords(table_name='job_job_history')

    def subtrair_disponnivel(self):
        job = Job.objects.filter(id=self.id)
        job.update(quantidade_vagas_disponiveis=job[0].quantidade_vagas_disponiveis - 1)

    def adicionar_disponnivel(self):
        job = Job.objects.filter(id=self.id)
        job.update(quantidade_vagas_disponiveis=job[0].quantidade_vagas_disponiveis + 1)

    def __str__(self):
        return str(self.acao)


class CorDaPeleJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_da_peles')
    cor_da_pele = models.ForeignKey(to='promotor.CorDaPele', on_delete=models.PROTECT,
                                    related_name='cores_da_peles')
    history = HistoricalRecords(table_name='job_cordapelejob_history')


class CorDoCabeloJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_dos_cabelos')
    cor_do_cabelo = models.ForeignKey(to='promotor.CorDoCabelo', on_delete=models.PROTECT,
                                      related_name='cores_dos_cabelos')
    history = HistoricalRecords(table_name='job_cordocabelojob_history')


class CorDosOlhosJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='cores_dos_olhos')
    cor_dos_olhos = models.ForeignKey(to='promotor.CorDosOlhos', on_delete=models.PROTECT,
                                      related_name='cores_dos_olhos')
    history = HistoricalRecords(table_name='job_cordosolhosjob_history')


class DisponibilidadeJob(models.Model):
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='disponibilidades_jobs')
    datahora_inicio = models.DateTimeField()
    datahora_fim = models.DateTimeField()
    history = HistoricalRecords(table_name='job_disponibilidadejob_history')


class Candidatura(models.Model):
    ATIVA = 1
    RETIRADA = 2
    SELECIONADA_ENTREVISTA = 3
    APROVADA = 4
    REPROVADA = 5
    REPROVADA_ENTREVISTA = 6

    STATUS = (
        (ATIVA, 'Ativa'),
        (RETIRADA, 'Retirada'),
        (SELECIONADA_ENTREVISTA, 'Selecionada para entrevista'),
        (APROVADA, 'Aprovada'),
        (REPROVADA, 'Reprovada'),
        (REPROVADA_ENTREVISTA, 'Reprovada na entrevista'),
    )

    promotor = models.ForeignKey(to='promotor.Promotor', on_delete=models.PROTECT, related_name='candidaturas')
    job = models.ForeignKey(to='Job', on_delete=models.PROTECT, related_name='candidaturas')
    status = models.PositiveIntegerField(choices=STATUS, default=1)
    observacao = models.CharField(max_length=255, null=True)
    data_hora_status = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords(table_name='job_categoria_history')

apps/job/views.py
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from apps.api.permissions import SuperUserRequiredMixin
from .forms import JobForm, TipoJobForm
from .models import Job, TipoJob


class TipoJobListView(SuperUserRequiredMixin, LoginRequiredMixin, ListView):
    model = TipoJob
    template_name = 'cadastros/tipojob/lista.html'
    context_object_name = "tipojob_lista"


class TipoJobCreateView(SuperUserRequiredMixin, LoginRequiredMixin, CreateView):
    model = TipoJob
    template_name = 'cadastros/tipojob/form.html'
    form_class = TipoJobForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-tipojob-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-tipojob-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class TipoJobUpdateView(SuperUserRequiredMixin, LoginRequiredMixin, UpdateView):
    model = TipoJob
    template_name = 'cadastros/tipojob/form.html'
    form_class = TipoJobForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-tipojob-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-tipojob-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class TipoJobDeleteView(SuperUserRequiredMixin, LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            obj = get_object_or_404(TipoJob, pk=pk)
            obj.delete()
            messages.success(request, 'Excluído(a) com sucesso')
        except:
            messages.error(request, 'Não foi possível excluir')
        return HttpResponseRedirect(reverse('cadastros-tipojob-list'))


class JobListView(LoginRequiredMixin, ListView):
    model = Job
    template_name = 'cadastros/job/lista.html'
    context_object_name = "job_lista"


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Job
    template_name = 'cadastros/job/form.html'
    form_class = JobForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-job-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-job-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class JobUpdateView(LoginRequiredMixin, UpdateView):
    model = Job
    template_name = 'cadastros/job/form.html'
    form_class = JobForm

    def get_success_url(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-job-list')

    def get_success_url_novo(self):
        messages.success(self.request, 'Salvo com sucesso')
        return reverse('cadastros-job-create')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        if 'outro' in self.request.POST:
            return HttpResponseRedirect(self.get_success_url_novo())
        else:
            return HttpResponseRedirect(self.get_success_url())


class JobDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            obj = get_object_or_404(Job, pk=pk)
            obj.delete()
            messages.success(request, 'Excluído(a) com sucesso')
        except:
            messages.error(request, 'Não foi possível excluir')
        return HttpResponseRedirect(reverse('cadastros-job-list'))


class CandidaturaView(LoginRequiredMixin, ListView):
    template_name = 'candidatos/lista.html'
    model = Job
    context_object_name = "job_lista"


class CandidaturaJogoView(LoginRequiredMixin, ListView):
    template_name = 'candidatos/jogo.html'
    model = Job
    context_object_name = "job_lista"

templates/cadastros/job/form.html
{% extends 'partials/layout.html' %} {% block content %}
    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui one column grid">
                    <div class="column">
                        <h2>
                            <i class="add circle icon"></i>Formulário de job</h2>
                    </div>
                </div>
                <div class="ui divider"></div>
            </div>
            <div class="column">
                <div class="ui form {% if form.errors %}error{% endif %}">
                    {{ form.non_field_errors }} {% if form.errors %}
                    <div class="ui error message">
                        <p>
                            {% if form.errors|length == 1 %} Por favor, corrija o erro abaixo. {% else %} Por favor,
                                corrija
                                os erros abaixo. {% endif %}
                        </p>
                    </div>
                {% endif %}
                    <form method="post" id="form" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}
                        {% for field in form.hidden_fields %} {{ field }} {% endfor %}
                        <div class="column">
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.acao class="four wide" label="Ação" %}
                                {% include 'partials/form_field.html' with field=form.tipo class="four wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.modo_pagamento label="" class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.observacao label="Observação" class="eight wide" %}
                            </div>
                            <h4 class="ui horizontal divider header">
                                <i class="users icon"></i> Quantidades de vagas
                            </h4>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.quantidade_vagas_totais label="Totais" class="four wide" %}
                                {% include 'partials/form_field.html' with field=form.quantidade_vagas_disponiveis label="Disponíveis" class="four wide" %}
                            </div>
                            <h4 class="ui horizontal divider header">
                                <i class="money bill alternate icon"></i>
                                Pagamento
                            </h4>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.quantidade_de_modo_pagamento label="Quant. de vezes que será pago" class="four wide" %}
                                {% include 'partials/form_field.html' with field=form.cache_por_modo_pagamento label="Valor pago por vez" class="four wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.cache_individual label="Valor individual" class="four wide" %}
                                {% include 'partials/form_field.html' with field=form.cache_total label="Total" class="four wide" %}
                            </div>
                            <h4 class="ui  horizontal divider header">
                                <i class="filter icon"></i>
                                Perfil
                            </h4>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.perfil_sexo label="Sexo" class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.perfil_idade_minima label="Idade mínima" class="two wide" %}
                                {% include 'partials/form_field.html' with field=form.perfil_idade_maxima label="Idade máxima" class="two wide" %}
                                {% include 'partials/form_field.html' with field=form.perfil_altura_minima label="Altura mínima" class="two wide" %}
                                {% include 'partials/form_field.html' with field=form.perfil_altura_maxima label="Altura máxima" class="two wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.cor_de_pele label="Cor da pele" class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.cor_do_cabelo label="Cor do cabelo" class="eight wide" %}
                            </div>
                            <div class="fields">
                                {% include 'partials/form_field.html' with field=form.cor_dos_olhos label="Cor dos olhos" class="eight wide" %}
                            </div>
                        </div>

                        <button type="submit" name="outro" class="ui labeled icon button teal right floated">
                            <i class="save icon"></i>
                            Salvar e cadastrar outro
                        </button>
                        <button type="submit" class="ui labeled icon button teal right floated">
                            <i class="save icon"></i>
                            Salvar
                        </button>
                        <a href="{% url 'cadastros-job-list' %}" class="ui labeled icon button black right floated">
                            <i class="cancel icon"></i>
                            Cancelar
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div id="load" class="ui active dimmer">
        <div class="ui text loader">Carregando</div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        const $quantidade_vagas_totais = $('#id_quantidade_vagas_totais');
        const $id_cache_individual = $('#id_cache_individual');
        const $id_cache_total = $('#id_cache_total');
        const $id_cache_por_modo_pagamento = $('#id_cache_por_modo_pagamento');
        const $id_quantidade_de_modo_pagamento = $('#id_quantidade_de_modo_pagamento');
        const $id_tipo = $('#id_tipo');

        $id_cache_individual.attr('readonly', true);
        $id_cache_total.attr('readonly', true);

        let FUNCAO = () => {
            if ($id_cache_por_modo_pagamento.val() && $id_quantidade_de_modo_pagamento.val() && $quantidade_vagas_totais.val()) {
                $id_cache_individual.val(parseFloat($id_quantidade_de_modo_pagamento.val()) * parseFloat($id_cache_por_modo_pagamento.val()));
                $id_cache_total.val(parseFloat($quantidade_vagas_totais.val()) * parseFloat($id_cache_individual.val()));
            }
        };

        $id_cache_por_modo_pagamento.change(function () {
            FUNCAO();
        });

        $id_quantidade_de_modo_pagamento.change(function () {
            FUNCAO();
        });

        $quantidade_vagas_totais.change(function () {
            FUNCAO();
        });

        function load(load) {
            if (load) {
                $('#load').addClass('active')
            } else {
                $('#load').removeClass('active')
            }
        }

        $.ajax({
            headers: {
                'Authorization': 'Token {{ user.token }}',
                'Content-Type': 'application/json'
            },
            type: 'GET',
            url: `${window.location.origin}/api/tipo-job/`,
            success: function (tipos) {
                localStorage.setItem('TIPOS_JOBS', JSON.stringify(tipos));
                load(false);
            },
            error: function (response) {
                load(false);
                toastr.error(response.responseJSON.detail);
            },

        });

        $id_tipo.change(function () {
            if ($id_tipo.val()) {
                let tipos = JSON.parse(localStorage.getItem('TIPOS_JOBS'));
                tipos = tipos.filter((x) => {
                    return x.id == $id_tipo.val()
                })[0];
                $('#id_modo_pagamento').val(tipos.modo_pagamento_sugerido);
            }
        });

    </script>
{% endblock %}

templates/cadastros/job/lista.html
{% extends 'partials/layout.html' %} {% block content %}
    <div class="ui segment">
        <div class="ui one column grid">
            <div class="column">
                <div class="ui two column grid">
                    <div class="column">
                        <h2>
                            <i class="list circle icon"></i>Lista de job</h2>
                    </div>
                    <div class="column">
                        <a href="{% url 'cadastros-job-create' %}"
                           class="ui labeled right floated icon button">
                            <i class="plus icon"></i>
                            Novo job
                        </a>
                    </div>
                </div>
                <div class="ui divider"></div>
                <table class="ui celled selectable compact table">
                    <thead>
                    <tr>
                        <th class="center aligned one wide">Código</th>
                        <th class="center aligned two wide">Ação</th>
                        <th class="center aligned two wide">Tipo</th>
                        <th class="center aligned one wide">Modo de pagamento</th>
                        <th class="center aligned one wide">Vagas totais</th>
                        <th class="center aligned one wide">Vagas disponíveis</th>
                        <th class="center aligned one wide">Quant. de vezes que será pago</th>
                        <th class="center aligned one wide">Valor pago por vez</th>
                        <th class="center aligned one wide">Valor individual</th>
                        <th class="center aligned one wide">Valor total</th>
                        <th class="center aligned two wide no-sort">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if job_lista %}
                        {% for job in job_lista %}
                            <tr>
                                <td>{{ job.id }}</td>
                                <td>{{ job.acao }}</td>
                                <td>{{ job.tipo }}</td>
                                <td>{{ job.get_modo_pagamento_display }}</td>
                                <td>{{ job.quantidade_vagas_totais }}</td>
                                <td>{{ job.quantidade_vagas_disponiveis }}</td>
                                <td>{{ job.quantidade_de_modo_pagamento }}</td>
                                <td>{{ job.cache_por_modo_pagamento }}</td>
                                <td>{{ job.cache_individual }}</td>
                                <td>{{ job.cache_total }}</td>
                                <td class="center aligned">
                                    <a href="{% url 'cadastros-job-update' job.id %}"
                                       class="ui icon tiny button green">
                                        <i class="edit icon"></i>
                                    </a>
                                    <a class="ui icon tiny button red"
                                       onclick="MODAL_APAGAR('Confirma a exclusão do job?', '{% url 'cadastros-job-delete' job.id %}')">
                                        <i class="trash icon"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="10">
                                <div class="ui ignored warning message">
                                    <b>Nenhuma job cadastrado.</b>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{% endblock %}